### ISSUE TITLE
Refactor workflow for pre/post processing

### ISSUE THREAD

**Issue by rabernat** [rabernat/floater#16]
Right now we have one code path for preprocessing of float input data (via generators.py) and a different one for postprocessing (via input.py). But the postprocessing scripts ([example](https://gist.github.com/rabernat/d45fa85bab2acbdb7643db853aa851ea)) always end up having to manually  re-create the ``FloatSet`` object which was used to generate the inputs. This seems inefficient and error prone.

It would be nice to have a more end-to-end workflow. I don't know exactly how this would look, but I am opening this issue so we can discuss it.

cc: @anirban89 @nathanieltarshish

**Comment by nathanieltarshish** [comment]
One cheap fix would be to build a feature that writes the relevant `FloatSet` parameters to a file and then modify the `Floatset` constructor:
```python
fs_foo = Floatset((10,20),(20,30),1,1) 
fs_foo.save('filepath')
fs_bar = Floatset('filepath') 
```

**Comment by rabernat** [comment]
Yes, @anirban89 and I have played around with using pickle for that.

My concern is that, if we have to store the land mask inside FloatSet, it will become huge and pickle might not be ideal anymore.

**Comment by nathanieltarshish** [comment]
Cannot speak to questions of optimality, but I have been using `panda`'s pickling functions to read/write the CM2p6 land mask. Just timed it: `to_pickle` took 76.9 ms and `read_pickle ` was 86.2 ms for the 39M land mask file.   Also, the FloatSet class currently does not have an attribute for `land_mask`.

**Comment by rabernat** [comment]
> the FloatSet class currently does not have an attribute for land_mask

Then how will be able to reconstruct the float's initial position given only ``npart`` (the "particle id")? This is part of why we need this refactor.

**Comment by nathanieltarshish** [comment]
Agreed. Could you point me towards code or an example in which the float's initial positions are mapped to `npart` and then reconstructed from `npart`? I am a bit confused as to how this happens since `npart_index_to_ndarray` in generators.py currently seems like a placholder.

**Comment by rabernat** [comment]
It is not yet implemented in generators.py. But it is in the helper.py module that came with the postprocessing scripts.

https://gist.github.com/rabernat/2792aeb190f6aa4869dc0d52f0763501#file-helper-py-L43

**Comment by nathanieltarshish** [comment]
Ah, thanks. By the way, what is the reasoning behind not including helper.py in the floater package? Seems to me that we will have to continually update as we build out `FloatSet`. For instance, looks like the current `dataseries_to_array` does not work correctly for a `FloatSet` with a land mask. 

What are your thoughts on creating a `save` function that instantiates and then pickles a `panda.Dataframe` that contains `land_mask`,  the `npart` data,  and any other data that would otherwise need to be manually re-created in post-processing ?

**Comment by rabernat** [comment]
> By the way, what is the reasoning behind not including helper.py in the floater package?

No grand reasoning! Just a random series of choices I made while trying to get stuff done! I guess that ``floater`` is supposed to be broad and generic, while ``helper.py`` has specific routines for a specific project. But that boundary is clearly not well defined.

> For instance, looks like the current dataseries_to_array does not work correctly for a FloatSet with a land mask.

Exactly. This is part of the problem.

> What are your thoughts on creating a save function that instantiates and then pickles a panda.Dataframe that contains land_mask, the npart data, and any other data that would otherwise need to be manually re-created in post-processing ?
 👍

**Comment by nathanieltarshish** [comment]
Okay, I'll make a branch over on my fork and work on it this week. If I understand correctly, we want to 
- include helper.py in floater package (or maybe just dump these functions into utils.py?) 
- modify `dataseries_to_array` to work with the masked `Floatset`
- make `land_mask` and `npart` attributes of the `FloatSet` class
- build an output data for post-processing feature which instantiates and then pickles a `panda.Dataframe` 
- write new constructor for FloatSet that loads in from pickled `panda.Dataframe `

Anything else?

**Comment by rabernat** [comment]
This is an ambitious refactor you are looking at. I would split it into atomic pieces as much as possible and make separate PRs for each one.

I don't think we just want to just blindly dump at the helper functions into floater. We want to think about the ideal API for our analysis workflow and then work backwards from that.

I think the way forward will become more clear after you have used the existing workflow for your own analysis at least once. So I recommend you first move forward with the science part of the project in order to gain experience with the different steps of this complex pipeline.

**Comment by nathanieltarshish** [comment]
> This is an ambitious refactor you are looking at. I would split it into atomic pieces as much as possible and make separate PRs for each one.

Okay, atomic changes makes sense. 

> I don't think we just want to just blindly dump at the helper functions into floater. We want to think about the ideal API for our analysis workflow and then work backwards from that.

For now, how about moving just `dataseries_to_array` into utils.py? 

> I think the way forward will become more clear after you have used the existing workflow for your own analysis at least once. So I recommend you first move forward with the science part of the project in order to gain experience with the different steps of this complex pipeline.

I agree, especially because there is continual pressure from above for me to get preliminary results on the science part. In my eyes, modifying `dataseries_to_array` to work with a masked `Floatset` is of high priority and essential to conducting the science part of the project.

**Comment by rabernat** [comment]
> continual pressure from above

I hope you're not referring to @StephenGriffies! 😉 

Let's not forget: the point of all this is the science... 🤓

**Comment by nathanieltarshish** [comment]
I think we can close this issue now, right?

**Comment by rabernat** [comment]
I think #29 together with #42 mostly have addressed this issue.
