### ISSUE TITLE
Question: RCLV search with periodic domains and masked regions

### ISSUE THREAD

**Issue by nathanieltarshish** [rabernat/floater#17]
With a global study of RCLV's in mind, I am wondering how compatible `hexgrid.find_convex_regions` is with domains that are periodic (about the East/West boundary) and also contain masked regions. If not currently compatible, how should we build out these features?

**Comment by rabernat** [comment]
Good point.

It would be a fairly small modification to hexgrid.pyx to enable periodicity. [Here](https://github.com/rabernat/floater/blob/master/floater/hexgrid.pyx#L122) is where the check for boundary points occurs, and just below is the code for identifying neighboring points on the hex grid.

**Comment by rabernat** [comment]
I guess we would want to add new keywords to the [constructor for HexArray](https://github.com/rabernat/floater/blob/master/floater/hexgrid.pyx#L38) like ``periodic_in_x=False, periodic_in_y=False``.

**Comment by nathanieltarshish** [comment]
> It would be a fairly small modification to hexgrid.pyx to enable periodicity. Here is where the check for boundary points occurs, and just below is the code for identifying neighboring points on the hex grid.

I think  `n_from_ji` can be adapted to handle periodicity. However, I don't see an easy way to modify `_is_convex()` to incorporate periodicity since `_point_in_poly` and `ConvexHull` do not seem to readily support periodicity.  @rabernat what is your take on this?

**Comment by nathanieltarshish** [comment]
We might want to consider conformally projecting the coordinates before calling above methods

**Comment by rabernat** [comment]
Not totally fixed yet...still have to deal with periodicity.
