### ISSUE TITLE
fixing a hexagonal tiling bug 

### ISSUE THREAD

**Issue by nathanieltarshish** [rabernat/floater#25]
The recent PR #23 created a slight bug in the `get_hexmesh` function. It essentially called  `_subset_floats_from_mask` twice by generating the uniform mask with `get_rectmesh`  instead of `xx, yy = np.meshgrid(self.x, self.y)`. I corrected this and made a few other cosmetic changes on the ` fix_get_hexmesh` branch on my fork and will submit a PR.

**Comment by rabernat** [comment]
Closed by #26
