### ISSUE TITLE
Issue with floating point arithmetic `Lx%dx` giving non zero values

### ISSUE THREAD

**Issue by anirban89** [rabernat/floater#3]
`xlim = [-60.0,-50.0]`
`Lx = 10.0`
`dx = 0.02`
gives value error because `if Lx%dx != 0.0: raise ValueError("Lx is not divisible evenly by dx")`
since `Lx%dx = 0.019999999999999792` in python.

**Comment by rabernat** [comment]
This example does not involve floater at all.

**Comment by anirban89** [comment]
`from floater import generators`
`fs = generators.FloatSet((-60.,-50.), (33.,40.5), dx = 0.02, dy = 0.015)`

gives:

`ValueError                                Traceback (most recent call last)
<ipython-input-13-cc6f9d19ba50> in <module>()
----> 1 fs = generators.FloatSet((-60.,-50.), (33.,40.5), dx = 0.02, dy = 0.015)
      2 plt.scatter(*fs.get_hexmesh())

/home/as4479/floater/floater/generators.py in __init__(self, xlim, ylim, dx, dy)
     26         self.Ly = ylim[1] - ylim[0]
     27         if (self.Lx % dx) != 0.0:
---> 28             raise ValueError("Lx is not divisible evenly by dx")
     29         if (self.Ly % dy) != 0.0:
     30             raise ValueError("Ly is not divisible evenly by dy")

ValueError: Lx is not divisible evenly by dx`

**Comment by rabernat** [comment]
Fixed by #4
